// Code generated by go generate; DO NOT EDIT.
// This file was generated from GraphQL schema ../../schema.graphql

package appsync

type Entity1 struct {
	Id        string    `json:"id"`
	Name      *string   `json:"name"`
	Regions   []string  `json:"regions"`
	Spaces    []*string `json:"spaces"`
	CreatedAt string    `json:"createdAt"`
	Total     *int64    `json:"total"`
}
